version: '3.8'

services:
  api:
    image: my_stack_api:latest
    ports:
      - "4000-4002:4000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    environment:
      - PORT=4000
      - DB=postgres://user1:password1@db:5432/busbud_db
    networks:
      - backend

  web:
    image: my_stack_web:latest
    ports:
      - "3000-3001:3000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    environment:
      - PORT=3000
      - API_HOST=http://api:4000
    networks:
      - backend

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: busbud_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user1", "-d", "busbud_db"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - api
      - web

networks:
  backend:
    driver: bridge

volumes:
  db_data:
